### ISSUE TITLE
Update Check 

### ISSUE THREAD

**Issue by Blanker101** [lewisakura/RFU#23] opened 2022-11-15 23:57 UTC
Every time I turn on my computer I always get the Update Check message saying I should update to 5.4.4 or whatever. I've already updated 3 times and it still thinks that I'm in a later version and need to update.

**Comment by lewisakura** [comment] 2022-11-16 09:20
What version is reported here?
![image](https://user-images.githubusercontent.com/8019327/202140395-f35fcd85-db6d-46a9-8683-e789127107aa.png)

**Comment by Blanker101** [comment] 2022-11-18 04:34
![image](https://user-images.githubusercontent.com/46302292/202617671-3f328c90-12ac-48c2-94a2-4f636d3a6a7d.png)
5.4.4, still getting the bug

**Comment by lewisakura** [comment] 2022-11-19 21:12
I can't reproduce the bug. It shouldn't be happening at all considering that version there is what it looks for on GitHub, so I have no idea what's going on here.

**Comment by lewisakura** [comment] 2023-01-08 13:23
Closing as a non-issue due to no followup and I can't reproduce it.

**Closed by lewisakura** 2023-01-08 13:23 UTC
Labels: bug
